package net.krusher.datalinks.exception;

public enum ErrorType {

    SERVER_ERROR,
    CAPTCHA_ERROR,
    PERMISSIONS_ERROR,
    USER_EXISTS,
    RESET_REQUEST_NOT_FOUND,
    USER_NOT_FOUND,
    USER_NOT_FOUND_OR_MAIL_MISMATCH,
    RESET_REQUEST_EXISTS,
    BAD_REQUEST,
    UPLOAD_ERROR,
    FILE_NOT_FOUND,
    PAGE_NOT_FOUND,

}
