quarkus.application.name=datalinks-backend

# === HTTP ===
quarkus.http.port=8080
%dev.quarkus.http.host=0.0.0.0
%prod.quarkus.http.host=127.0.0.1
quarkus.http.proxy.proxy-address-forwarding=true
quarkus.http.body.handle-file-uploads=true
quarkus.http.limits.max-body-size=5M

# === Datasource placeholders ===
quarkus.datasource.db-kind=mariadb
quarkus.datasource.jdbc.url=
quarkus.datasource.username=
quarkus.datasource.password=

%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:datalinks;DB_CLOSE_DELAY=-1
%test.quarkus.hibernate-orm.database.generation=drop-and-create
%test.quarkus.hibernate-orm.sql-load-script=import-test.sql

# === Mailer for tests ===
%test.quarkus.mailer.mock=true
%test.quarkus.mailer.log=true
%test.quarkus.mailer.host=localhost
%test.quarkus.mailer.port=8025
%test.quarkus.mailer.from=test@example.com

# === App config for tests ===
%test.application.sitename=Datalinks Test
%test.application.upload.dir=./target/uploads
%test.application.url=http://localhost:8081
%test.application.backend.url=http://localhost:8081
%test.google.recaptcha.key.secret=dummy-secret
%test.google.recaptcha.key.site=dummy-site

# === Hibernate ORM ===
quarkus.hibernate-orm.database.generation = update
%dev.quarkus.hibernate-orm.log.sql=true
%dev.quarkus.hibernate-orm.log.format-sql=false
%prod.quarkus.hibernate-orm.log.sql=false

google.recaptcha.key.site=
google.recaptcha.key.secret=

# === CORS for dev profile ===
%dev.quarkus.http.cors.enabled=true
%dev.quarkus.http.cors.origins=http://localhost:5173,http://192.168.42.5:5173,http://192.168.1.66:5173
%dev.quarkus.http.cors.methods=HEAD,GET,POST,PUT,DELETE,PATCH,OPTIONS
%dev.quarkus.http.cors.access-control-allow-credentials=true

# === Logging, use quarkus.log.file.path for file ===
quarkus.log.level=INFO
