quarkus.application.name=datalinks-backend

# === HTTP ===
quarkus.http.port=8080
%dev.quarkus.http.host=0.0.0.0
%prod.quarkus.http.host=127.0.0.1
quarkus.http.proxy.proxy-address-forwarding=true
quarkus.http.body.handle-file-uploads=true
quarkus.http.limits.max-body-size=5M

# === Datasource (placeholders, se sobreescriben por datalinks.properties) ===
quarkus.datasource.db-kind=mariadb
quarkus.datasource.jdbc.url=
quarkus.datasource.username=
quarkus.datasource.password=

# === Hibernate ORM ===
quarkus.hibernate-orm.database.generation=update
%dev.quarkus.hibernate-orm.log.sql=true
%prod.quarkus.hibernate-orm.log.sql=false

google.recaptcha.key.site=
google.recaptcha.key.secret=

# === CORS (solo dev, equivalente a DevConfig) ===
%dev.quarkus.http.cors.enabled=true
%dev.quarkus.http.cors.origins=http://localhost:5173,http://192.168.42.5:5173,http://192.168.1.66:5173
%dev.quarkus.http.cors.methods=HEAD,GET,POST,PUT,DELETE,PATCH,OPTIONS
%dev.quarkus.http.cors.access-control-allow-credentials=true

# === Logging ===
%prod.quarkus.log.file.enable=false
quarkus.log.level=INFO
